### PR TITLE
Make controller class customizable

### PR DESCRIPTION
**Pull request by abejenaru**
Add config entry for Settings CRUD controller class; allows to only overwrite the controller class, without touching the routing.

### CODE REVIEW

**Comment by pxpm** [comment]
Hey @abejenaru ! Thanks for the PR. 

I am NOT totally sure that we should do this. I will try to explain my rationale to see if it fits the bill. 
I am ok, and agree having configurable route names when they possible conflict with some other major package. I am ok with database table name, it's a general name, could conflict ... yeah. But I don't have the same feeling about this. I think this is just overkill as I think 99,99% of the people would not be using this configuration, contrary to the others I mention, where I think they will be useful for maybe 10% of people. 🙃 

If you need to extend the package controller you should create your own controller that extends the package one, and bind your controller in the service provider.

```php
// controller

class YourController extends \Backpack\Settings\app\Http\Controllers\SettingCrudController
{
    public function setup()
    {
        parent::setup();
       
        CRUD::setEntityNameStrings('your new entity string', 'your new entity strings');
    }
}

// service provider
    public function boot()
    {
        $this->app->bind(\Backpack\Settings\app\Http\Controllers\SettingCrudController::class, \App\YourController::class);
    }
```

Let me know what you think! 👍 

Best,
Pedro

**Comment by abejenaru** [comment]
Thanks Pedro, I don't have a strong commitment for this change.
If you think it's something even less likely to be customized than the other stuff, and for these rare cases there are Laravel's built-in mechanisms to extend/overwrite any functionality, then by all means it doesn't have to be part of the package.
Cheers, Andrei

**Comment by tabacitu** [comment]
Thanks for taking the time to submit the PR @abejenaru ! And a very clean one, by the way, thank you 🙏

I was torn about merging this too. Like @pxpm said... it's difficult to decide where to draw the line... At first I was going to say "_fuck it, let's merge it, it's a clean PR_", but then I realised... what about the Model? 😅 Should we let people override that one too? And if so, how? Should we add a new config for it? How about the Request then? See... it's a slippery slope.

So yeah, I'm now more confident in my opinion that @pxpm was right. I think a good rule of thumb for us would be to:
- provide a config for what Laravel doesn't make easy to override;
- instruct people to use `bind()` for PHP classes, since Laravel's default override mechanism works well enough;

So I'm afraid I'm going to close this PR @abejenaru . Sorry this one didn't get merged - we do appreciate the effort you put into it, and like I said, we appreciate how clean it is 😀

Cheers!

**Comment by abejenaru** [comment]
Thanks @tabacitu and @pxpm for taking the time and writing a comprehensive argument.
Keep up the great work on Backpack products 👍

**Pull request closed without merging**
