### PR TITLE
Fixed error with field attributes

### PR DESCRIPTION
**Pull request by adriandmitroca**
Plain casting to an array does not convert nested arrays, which causes `attributes` parameter remained as stdClass by default. 

This PR fixes that behavior, making `attributes` an actual array that doesn't break edit page.

### CODE REVIEW

**Comment by iMokhles** [comment]
I thought about using serialize() unserialize() which should fix this issue also,  one time for all and using casting field column to array in the model so we clean more the code,  what do you think?

**Comment by adriandmitroca** [comment]
Serialized data structures are a bit harder to maintain and manually edit (also this would be pretty big BC).

Using existing concept seems a lot more straightforward to me and what's more important, can be applied in a minor version.

**Comment by iMokhles** [comment]
oh I didn't notice before that there are already pull request similar to yours
https://github.com/Laravel-Backpack/Settings/pull/44

**Comment by adriandmitroca** [comment]
Please merge & release 🙌

@tabacitu

**Comment by tabacitu** [comment]
Merged & released! Thank you @adriandmitroca !

**Pull request merged**
